services:
  web:
    build: .
    container_name: django_webapp
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/static
    depends_on:
      - web
