# Generated by Django 5.2.2 on 2025-06-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_feedback_email_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(default='this site rocks', max_length=500),
            preserve_default=False,
        ),
    ]
